.github/workflows/actions.yaml
Removing broken actions while they are getting resolved.
Currently the Unit test and Forbidden work checks in actions are going to have false negatives due to issues with both checks. This is an actions update only and does not apply to the checklist below.
| |
- N/A - Actions update only
=> Updating broken actions

dell-csi-helm-installer/common.sh, dell-csi-helm-installer/csi-install.sh, dell-csi-helm-installer/csi-uninstall.sh
This PR updates dell-csi-helm-installer with:
- _uninstallerror_ message
- points _values_ to driver-image and Kubernetes version file
=> Addressing installation review comments across all drivers

.build.config, .build.config.user, build.sh, helm/csi-powermax/values.yaml
This PR ,
Updating the build scripts
Updating latest UBIM image   
|  #[102 ](https://github.com/dell/csm/issues/102)    |
=> updating build server and ubim version

helm/csi-powermax/values.yaml
Removing example section for csm-authorization and csi-replicator side car
|      #[109  ](https://github.com/dell/csm/issues/109)               |
=> Removing image example

helm/csi-powermax/values.yaml
Updated replicator sidecar image
| Release https://github.com/dell/csm/milestone/2 |
=> Updated replicator sidecar image

dell-csi-helm-installer/verify-csi-powermax.sh, helm/csi-powermax/k8s-1.21-values.yaml, helm/csi-powermax/k8s-1.22-values.yaml, helm/csi-powermax/k8s-1.23-values.yaml, plugin.go, service/envvars.go
This PR contains
1. New sample file for k8 1.23
2. Updated K8 supported versions 
|    #[136  ](https://github.com/dell/csm/issues/136)        |
=> Adding 1.23 support

csireverseproxy/go.mod, csireverseproxy/go.sum
Updates go powermax image to 1.6 (latest) in revproxy
| |
Build, Unit tests
=> Upgrades gopmax image in revproxy

service/features/controller_publish_unpublish.feature, service/features/node_publish_unpublish.feature, service/features/service.feature, service/step_defs_test.go, test/integration/features/integration.feature, test/integration/step_defs_test.go
Unit test and integration test for SINGLE_NODE_SINGLE_WRITER and SINGLE_NODE_MULTI_WRITER for kubernetes 1.22+
|   https://github.com/dell/csm/issues/175              |
=> Unit test and integration test  for RWOP

.build.config
Updating UBIM image to latest 8.5-230
| https://github.com/dell/csm/issues/183|
=> updating ubim image

README.md
Update for Contribution guidelines for the CSI Driver for PowerMax
| https://github.com/dell/csm/issues/177 |
=> Feature 177 update readme

Dockerfile.build, README.md, clamavscan.sh, dell-csi-helm-installer/README.md, dell-csi-helm-installer/csi-offline-bundle.md, helm/README.md, helm/csi-powermax/values.yaml
Changed DellEMC branding to Dell
| |
=> Changed DellEMC branding to Dell

go.mod, go.sum
Changed go.mod file to point to correct tags
| https://github.com/dell/csm/issues/128 |
=> Use full tags for new version of dell-csi-extensions

helm/csi-powermax/values.yaml
Bumped up sidecar version
| https://github.com/dell/csm/issues/220 |
No impact on any release processes, all development and testing already done on latest version
=> Bumped up sidecar version

Dockerfile.build
It fixes the dirty bit in the driver image
|https://github.com/dell/csm/issues/222 |
Driver image build and driver logs
=> Removing dirty bit

helm/csi-powermax/Chart.yaml
Updated k8 supported versions 
|https://github.com/dell/csm/issues/247 |
=> updating supported k8 versions

csireverseproxy/go.mod, csireverseproxy/go.sum
Fixing dependabot alerts 
| https://github.com/dell/csm/issues/280 |
=> Fixing dependabot alerts 

service/controller.go, service/features/service.feature, service/service_test.go, service/service_unit_test.go, service/step_defs_test.go
Namespace mapping to PV/PVC
|https://github.com/dell/csm/issues/272 |
=> Volume to namespace mapping on array

samples/storageclass/powermax.yaml
Annotation to set the default SC is not beta anymore
|  https://github.com/dell/csm/issues/281 |
=> Annotation to set the default SC is not beta anymore

service/controller.go, test/integration/README, test/integration/features/integration.feature, test/integration/step_defs_test.go
Enables remote volume cleanup during integration tests.
| |
Integration test, Unit test
=> Updates Int test with remote client

csireverseproxy/main.go, csireverseproxy/main_test.go, csireverseproxy/pkg/cache/cache.go, csireverseproxy/pkg/common/common.go, csireverseproxy/pkg/config/config.go, csireverseproxy/pkg/config/config_test.go, csireverseproxy/pkg/k8smock/k8smock_test.go, csireverseproxy/pkg/standaloneproxy/standaloneproxy.go, csireverseproxy/pkg/utils/locks.go, csireverseproxy/pkg/utils/utils.go, service/controller.go, service/deletion_worker.go, service/locks.go, service/node.go, service/service.go, service/snap.go, service/step_defs_test.go, service/string_slice.go
Removing line feed
| https://github.com/dell/csm/issues/251|
=> Removing line feed

helm/csi-powermax/templates/node.yaml
Fix for - Installation of power max is failing with parser error 
| https://github.com/dell/csm/issues/302 |
=> Installation fix for the parser error 

helm/csi-powermax/templates/_helpers.tpl
Updating sidecar version for node-registrar and health monitor . 
| https://github.com/dell/csm/issues/243 |
=> Updating sidecar versions

helm/csi-powermax/values.yaml
Updating node selector keys
| |https://github.com/dell/csm/issues/319 
=> Updating node selector keys

helm/csi-powermax/templates/node.yaml
Updates node template to point to correct topology param.
|https://github.com/dell/csm/issues/326 |
Cluster Testing:
=> Updates node template to point to correct topology param

.build.config
updating latest ubim latest  image - 8.6-751
| https://github.com/dell/csm/issues/243 |
=> updating latest ubim image

go.mod, go.sum
Updating goiscsi which has fix for DiscoverTargets for Powermax. 
| https://github.com/dell/csm/issues/330 |
=> Updating goiscsi commit

service/node.go
Fixes bug to create hosts with node IQNs if no valid initiators are found on unisphere.
|https://github.com/dell/csm/issues/335 |
Cluster Tests:
```
time="2022-06-08T12:41:40Z" level=info msg="valid initiator: SE-1E:000:iqn.1993-08.org.debian:01:83ae35a8f65d\n"
time="2022-06-08T12:41:40Z" level=info msg="valid (existing) iSCSI initiators (must be manually created): [iqn.1993-08.org.debian:01:83ae35a8f65d]"
time="2022-06-08T12:41:40Z" level=info msg="ISCSI Daemon is active"
time="2022-06-08T12:41:40Z" level=info msg="setting up array 000197902417 for Iscsi, host name: csi-node-worker-2-gznjqykjf0w0c-host masking view ID: csi-mv-ABY-worker-2-gznjqykjf0w0c"
time="2022-06-08T12:41:40Z" level=debug …
```
=> Updates validIscsis to IQNs if validIscsis zero

csireverseproxy/manifests/revproxy.yaml, helm/csi-powermax/charts/csireverseproxy/values.yaml, helm/csi-powermax/values.yaml
Signed-off-by: Dubey <Utkarsh.Dubey@Dell.com>
| https://github.com/dell/csm/issues/243|
Cluster Tests
=> Updating revproxy images version

.github/workflows/actions.yaml
Use the gosec action from common-github-actions to get gosec passing again -- see this PR for further details: https://github.com/dell/common-github-actions/pull/63
| https://github.com/dell/csm/issues/350 |
Ran actions, confirmed passing
=> Get gosec passing again

service/node.go
Update node.go for powerpath volume expansion
| https://github.com/dell/csm/issues/436 |
=> Resize Powerpath devices

go.mod, go.sum, service/controller.go, service/deletion_worker.go, service/migration.go, service/replication.go
Signed-off-by: Utkarsh Dubey <Utkarsh.Dubey@Dell.com>
* Fixes auto-srdfg for volume migrate cases.
* Limits async replication for namespace within 7 char
|https://github.com/dell/csm/issues/411 |
- Unit test
544 scenarios (544 passed)
3865 steps (3865 passed)
PASS ok
- Cluster test
[volumeMigrationDriver.txt](https://github.com/dell/csi-powermax/files/9437292/volumeMigrationDriver.txt)
=> Fixes auto-srdfg for volume migration

helm/csi-powermax/values.yaml
Update Authorization sidecar to latest 1.4.0 image
| https://github.com/dell/csm/issues/448 |
=> Update Authorization sidecar image to 1.4.0

.build.config
Update latest UBI image 
|https://github.com/dell/csm/issues/350  |
=> Update UBI image

helm/csi-powermax/templates/_helpers.tpl
Update latest sidecar version . 
| https://github.com/dell/csm/issues/350 |
=> Updating latest sidecars

csireverseproxy/Dockerfile, helm/csi-powermax/charts/csireverseproxy/Chart.yaml
Updating api version for Proxy 
| https://github.com/dell/csm/issues/350 |
=> Updating Proxy version

.build.config
Updating UBI minimal latest image
| https://github.com/dell/csm/issues/350 |
=> Updating UBI minimal image

build.sh, csireverseproxy/Dockerfile
Fixed the build failure
| https://github.com/dell/csm/issues/537 |
Ran the build, it is successfully going through
=> Fix build failure - CSI PowerMax

service/controller.go
This PR switched the publish context WWN to have value from effective_wwn than native WWN.
|https://github.com/dell/csm/issues/542 |
- Cluster Testing
=> Switch to effective wwn 

helm/csi-powermax/values.yaml
PR to update the Authorization image for the CSM 1.5 release.
| https://github.com/dell/csm/issues/491|
=> Update Authorization sidecar image

service/controller.go
- Fixes removing vSphere volume from the correct masking view
| https://github.com/dell/csm/issues/544|
- Unit Tests
=> ControllerUnpublish Fix: reading vSphere masking view

dell-csi-helm-installer/verify-csi-powermax.sh
Updating verify script with latest OpenShift version
|https://github.com/dell/csm/issues/557
https://github.com/dell/csm/issues/480 |
=> Updating verify script with latest OpenShift version

service/node.go, service/vsphere.go
- Enhances cleanup of RDM devices on the host
|https://github.com/dell/csm/issues/562|
- Cluster Test
- Unit Test
=> Updates DisconnectVolume to clean up RDM devices 

samples/storageclass/powermax_srdf.yaml
Bug Fix - Updated sample class file with SRDF group mandate to optional 
| https://github.com/dell/csm/issues/641 |
=> Bug Fix - Updated sample class file with SRDF group mandate to optional 

service/controller.go, service/features/replication.feature, service/step_defs_test.go
- Enables CSI Driver to create clones of SRDF vols.
- Creates new PVCs with source PVC as protected volumes.
- Adds unit tests
| https://github.com/dell/csm/issues/646|
- Unit Tests
=> Enables CSI Driver to create clones of SRDF vols

helm/csi-powermax/templates/_helpers.tpl
Updating latest sidecar versions.
Attacher - 4.2.0
Provisioner - 3.4.0
Resizer - 1.7.0
Snapshotter - 6.2.1
Registrar - 2.6.3
Health-monitor - 0.8.0
| https://github.com/dell/csm/issues/583 |
=> Updating sidecars

Dockerfile.build, csireverseproxy/Dockerfile, csireverseproxy/manifests/revproxy.yaml, dell-csi-helm-installer/csi-install.sh, helm/csi-powermax/Chart.yaml, helm/csi-powermax/charts/csireverseproxy/Chart.yaml, helm/csi-powermax/values.yaml
1.Updating driver version to v2.6.0
2.Updating reverseproxy version to v2.5.0
| https://github.com/dell/csm/issues/583 |
=> Bumping the driver version

helm/csi-powermax/values.yaml
PR to update authorization sidecar version to align with CSM release 1.6.0.
|https://github.com/dell/csm/issues/583 |
=> Update module sidecar version

pkg/migration/migration.go, service/migration.go
- Updates Migration to skip creating migration session for empty SGs
|https://github.com/dell/csm/issues/705 |
- Unit test
- Cluster test
=> Updates migration to skip empty SGs

helm/csi-powermax/templates/_helpers.tpl
Update K8s image registry to registry.k8s.io.
| https://github.com/dell/csm/issues/744 |
=> Change K8s registry to registry.k8s.io

dell-csi-helm-installer/verify-csi-powermax.sh
Update the supported OpenShift versions
| https://github.com/dell/csm/issues/571 
https://github.com/dell/csm/issues/724
|
=> Update the supported OpenShift versions

helm/csi-powermax/templates/csidriver.yaml
Updates default driver name to its full name.
| https://github.com/dell/csm/issues/789|
- Cluster Test
=> Updates default driver name to its full name

dell-csi-helm-installer/verify-csi-powermax.sh, helm/csi-powermax/Chart.yaml, helm/csi-powermax/templates/_helpers.tpl
Adding kubernetes 1.27 support 
| https://github.com/dell/csm/issues/761|
=> Adding k8_27 support

helm/csi-powermax/values.yaml, service/controller.go, service/node.go, service/storage_group_svc.go
|https://github.com/dell/csm/issues/746 |
- [X ] Have you run format,vet & lint checks against your submission?
- [X ] Have you made sure that the code compiles?
- [X ] Did you run the unit & integration tests successfully?
- [X ] Have you commented your code, particularly in hard-to-understand areas
- [X ] Did you run tests in a real Kubernetes cluster?
- [X ] Backward compatibility is not broken
=> Feature: Adds support for hostgroup for vsphere environment. 

service/mount.go
Remove the readOnly flag for block volume
|https://github.com/dell/csm/issues/792 |
- Cluster Test
=> Remove readOnly flag for block volume

csireverseproxy/Makefile, csireverseproxy/deploy/config.yaml, csireverseproxy/main.go, csireverseproxy/main_test.go, csireverseproxy/pkg/config/config.go, csireverseproxy/pkg/config/config_test.go, csireverseproxy/pkg/linkedproxy/linkedproxy.go, csireverseproxy/test-config/config.yaml, helm/csi-powermax/charts/csireverseproxy/conf/config.yaml, helm/csi-powermax/values.yaml
Revert "remove linked proxy mode"
|https://github.com/dell/csm/issues/757 |
- Cluster Test
=> Revert "remove linked proxy mode"

pkg/migration/migration.go, service/controller.go, service/features/node_publish_unpublish.feature
- Check if there are any limits for the SG
- If none, send a nil struct to gopowermax
|https://github.com/dell/csm/issues/797|
- Unit test:
557 scenarios (557 passed)
3928 steps (3928 passed) PASS ok
- Cluster test
=> Setting HostIOLimits struct to nil if no limits applied

service/controller.go, service/features/delete_volume.feature, service/features/replication.feature, service/service_test.go, service/step_defs_test.go, test/integration/features/integration.feature, test/integration/integration_test.go, test/integration/step_defs_test.go
- Delete Local Volume on the remote array based on its retention Policy.
- Updates Unit Tests
- Updates Integration Tests
| https://github.com/dell/csm/issues/801|
- Unit Test
564 scenarios (564 passed)
3968 steps (3968 passed) PASS
- Cluster Test
=> Feature: Delete local volume on remote array 

helm/csi-powermax/Chart.yaml, helm/csi-powermax/charts/csireverseproxy/templates/certificate.yaml, helm/csi-powermax/charts/csireverseproxy/values.yaml, helm/csi-powermax/templates/_helpers.tpl, helm/csi-powermax/values.yaml, service/node.go
Adding support to create reverseproxy certs automatically . 
|https://github.com/dell/csm/issues/819 |
=> Feature 819 auto certs proxy

helm/csi-powermax/values.yaml
Updating csm authorization sidecar to 1.7.0
|https://github.com/dell/csm/issues/743 |
=> Update auth sidecar to 1.7.0

.build.config, build.sh
Added sha to pull the ubi micro image
=> Added sha to pull the ubi micro image

service/features/service.feature
| [GitHub Issue # ](https://github.com/dell/csm/issues/844)|
=> Update volumename to have namespace

dell-csi-helm-installer/verify-csi-powermax.sh
Added new OpenShift version in verification script 
| https://github.com/dell/csm/issues/724 |
=> Added new OpenShift version in verification script 

dell-csi-helm-installer/README.md, dell-csi-helm-installer/csi-offline-bundle.sh
Changing offline install script to use common helm charts. 
|https://github.com/dell/csm/issues/877|
root@dldv2014:~/v2.8.0/csi-powermax/dell-csi-helm-installer#  bash  csi-offline-bundle.sh -c
*
* Building image manifest file
Processing files in /root/v2.8.0/csi-powermax/helm-charts/charts/csi-powermax
dellemc/csi-powermax\:v2.7.0
*
* Pulling and saving container images
dellemc/csipowermax-reverseproxy:v2.6.0
dellemc/csi-powermax:v2.7.0
dellemc/csm-authorization-sidecar:v1.7.0
dellemc/dell-csi-migrator:v1.1.1
dellemc/dell-csi-node-rescanner:v1.0.0 …
=> Updating offline install changes

dell-csi-helm-installer/csi-install.sh, dell-csi-helm-installer/verify.sh
Updating verification script for k8 1.28 
|https://github.com/dell/csm/issues/947 |
=> Updating verify script

go.mod, go.sum
Updating latest go library commits
|https://github.com/dell/csm/issues/885 |
=> Updating latest GO commits

samples/storageclass/powermax_nfs.yaml, service/controller.go, service/features/controller_publish_unpublish.feature, service/features/delete_volume.feature, service/features/migration.feature, service/features/replication.feature, service/migration.go
Updates err msg and block unsupported for NFS Volume
|https://github.com/dell/csm/issues/861|
- Unit Tests
=> Updates err msg and block unsupported for NFS Volume

service/controller.go
Adds unsupported response for NFS static provisioning
|https://github.com/dell/csm/issues/861|
- Unit Tests
=> Adds unsupported response for NFS static provisioning

Dockerfile, Dockerfile.build, buildubimicro.sh
Installing dependency packages to support powerpath expansion 
| https://github.com/dell/csm/issues/976|
=> Update build packages

service/mount.go
Returning true/success once the directory is created for mounting.
|https://github.com/dell/csm/issues/1014|
- Unit Tests
569 scenarios (569 passed)
3990 steps (3990 passed)
PASS
=> Returning true/success once directory is created

.build.config
Updating latest UBI 9 micro image tag
|https://github.com/dell/csm/issues/1012 |
=> Updating latest UBI

Dockerfile.build, dell-csi-helm-installer/README.md, dell-csi-helm-installer/csi-install.sh, dell-csi-helm-installer/csi-offline-bundle.sh
Adding support for 2.9.0 
|https://github.com/dell/csm/issues/1012 |
=> Bump the driver version

samples/storageclass/powermax.yaml, samples/storageclass/powermax_xfs.yaml
UPdated commnet section for the allowed  values  for "nfs"
=> Comments updated storageclasses

Dockerfile
Fixing the `make docker `command failure 
| https://github.com/dell/csm/issues/1051 |
Executed make docker command and it is running successfully
=> make docker command is failing

Makefile
Installing Golint if not available via Go install 
| https://github.com/dell/csm/issues/1061 |
=> Installing Golint if not available via go install 

csireverseproxy/main.go, csireverseproxy/pkg/k8smock/k8smock.go, csireverseproxy/pkg/k8sutils/k8sutils.go
| |
- [x} Have you maintained at least 90% code coverage?
- Unit test
=> GOSEC updates for reverseproxy

service/controller.go
- Adds refresh symmetrix call to update the cache if Metro WWN is not synced across devices.
-
| |
- Unit Test
- Cluster Test
=> Refresh symmetrix to update the cache for wwn

dell-csi-helm-installer/csi-offline-bundle.md
Update documentation for offline bundle installation.
|https://github.com/dell/csm/issues/1081|
=> Update documentation for offline bundle

Dockerfile.build, dell-csi-helm-installer/README.md, dell-csi-helm-installer/csi-install.sh, dell-csi-helm-installer/csi-offline-bundle.sh
=> Updating scripts to 2.9.1

.github/workflows/linters.yaml
Update of go version used in linters actions.
=> update go version in linters action

Dockerfile.build, dell-csi-helm-installer/README.md, dell-csi-helm-installer/csi-install.sh, dell-csi-helm-installer/csi-offline-bundle.md, dell-csi-helm-installer/csi-offline-bundle.sh, service/deletion_worker.go, service/mount.go, service/node.go, service/storage_group_svc.go
Updating csm version from 2.9.0 to 2.10.0
| https://github.com/dell/csm/issues/1091|
=> Bump the csm version

service/controller.go
Compare the wwn for local and remote vol and do a refresh on symmetrix.
|https://github.com/dell/csm/issues/1175|
- Unit Test
- Cluster test
=> Compare the wwn for local and remote vol and do a refresh on symmetrix  

go.mod, go.sum
Update latest go brick
|https://github.com/dell/csm/issues/1091  |
=> Update latest go brick

README.md
Update doc links in Readme
|https://github.com/dell/csm/issues/1209 |
=> Update doc links in Readme

Dockerfile.build, csireverseproxy/Dockerfile, dell-csi-helm-installer/README.md, dell-csi-helm-installer/csi-install.sh, dell-csi-helm-installer/csi-offline-bundle.md, dell-csi-helm-installer/csi-offline-bundle.sh, dell-csi-helm-installer/verify-csi-powermax.sh, dell-csi-helm-installer/verify.sh
Adding support for OCP 4.15 in check
Bumping version from 10.0 to 10.2
|https://github.com/dell/csm/issues/1280 |
=> Changes for CSM 1.10.2 release

dell-csi-helm-installer/verify.sh
Update cert-csi link 
|https://github.com/dell/csm/issues/1280 |
=> update cert-csi link

buildubimicro.sh, csireverseproxy/Dockerfile
This PR updates the UBI micro dependencies.
Gihub Issue #:
https://github.com/dell/csm/issues/1221
I have tested this change locally ( by running bash ./build.sh -i ubimicro -pyoer 1258 ) and verified that all images have been created and rpm is added.
=> Update ubi dependencies

csireverseproxy/Dockerfile, csireverseproxy/Makefile, csireverseproxy/buildubimicro.sh
This PR will update make file to build image locally.
| (https://github.com/dell/csm/issues/1221) |
| |
I have tested it locally .
=> Update Makefile to build reverseproxy

go.mod, go.sum, samples/storageclass/powermax_nvmetcp.yaml, service/controller.go, service/node.go
- Updates gonvme package to use latest parser
- Adds NVMe sample storage class
- Adds changes lost due to rebase in last PR
|https://github.com/dell/csm/issues/1346|
=> Updates gonvme package to use latest parser

dell-csi-helm-installer/verify-csi-powermax.sh
This PR updates the OCP version to 4.16.
|https://github.com/dell/csm/issues/1359 |
Installed on OCP 4.16
=> Update OCP Version

.github/workflows/actions.yaml, csireverseproxy/pkg/standaloneproxy/standaloneproxy.go
| https://github.com/dell/csm/issues/1221 |
=> Update gosec actions.yaml

csireverseproxy/pkg/standaloneproxy/standaloneproxy.go
Re add mux library
| https://github.com/dell/csm/issues/1221 |
Unit Test:
=> Re add mux library

csireverseproxy/pkg/standaloneproxy/standaloneproxy.go
| https://github.com/dell/csm/issues/1221 |
=> Gosec CVE fix

service/envvars.go, service/service.go
Implemented required changes for the minimal manifests.
| https://github.com/dell/csm/issues/1449 |
1. Tested by running in the kubernetes cluster
2. Ran unit tests
=> Feature/minimal CRD

samples/configmap/powermax-array-config.yaml
Updated sample array configmap file 
| https://github.com/dell/csm/issues/1449 |
Created the configmap in the kubernetes cluster
=> Added array config sample file

go.mod, go.sum
Update gobrick to latest commit.
| https://github.com/dell/csm/issues/1447 |
| https://github.com/dell/csm/issues/1435 |
=> Update gobrick to latest commit

test/integration/step_defs_test.go
Description
This change was missed in the previous PR to solve the test cases failure.
|--- |
| https://github.com/dell/csm/issues/1519 |
How Has This Been Tested?
Test is already been done in the last PR.
=> PowerMax Integration test failures

test/helm/1clonevol/templates/pvc0.yaml, test/helm/2vols+restore/templates/createFromSnap.yaml, test/helm/2vols+restore/templates/pvc0.yaml, test/helm/2vols+restore/templates/pvc1.yaml, test/helm/2vols+restore/templates/test.yaml, test/helm/snaprestoretest.sh, test/helm/starttest.sh
merging changes from one branch into another
=> helm fixes

dell-csi-helm-installer/verify-csi-powermax.sh
Updating the support for k8s version and OCP for powermax 2.12
| https://github.com/dell/csm/issues/1472
https://github.com/dell/csm/issues/1473 |
- Ran cert-csi on k8s-1.31 
[pmax-k8s-1.31-cert-csi.txt](https://github.com/user-attachments/files/17465906/pmax-k8s-1.31-cert-csi.txt)
- ran cert-csi on pmax-4.17
[pmax-ocp-4.17- cert-csi.txt](https://github.com/user-attachments/files/17465957/pmax-ocp-4.17-.cert-csi.txt)
=> Update K8s and OCP version

Dockerfile, Makefile, csireverseproxy/Dockerfile, dell-csi-helm-installer/README.md, dell-csi-helm-installer/csi-install.sh, dell-csi-helm-installer/csi-offline-bundle.md, dell-csi-helm-installer/csi-offline-bundle.sh
Version update for CSM 1.12
| https://github.com/dell/csm/issues/1435 |
Successfully built all images with these changes
Ran cert-csi and it passed with 100%
```
[2024-10-24 14:29:32]  INFO Avg time of a run:   25.05s
[2024-10-24 14:29:32]  INFO Avg time of a del:   12.02s
[2024-10-24 14:29:32]  INFO Avg time of all:     47.31s
[2024-10-24 14:29:32]  INFO During this run 100.0% of suites succeeded
```
=> Version update for CSM 1.12

service/features/service.feature
Fix one unit test failure.
| https://github.com/dell/csm/issues/1435 |
unit test passed
=> Fix Unit Test

csireverseproxy/go.mod, csireverseproxy/go.sum
golang.org/x/net pkg update
| https://github.com/dell/csm/issues/1559 |
=> golang.org/x/net pkg update

csireverseproxy/go.mod, csireverseproxy/main_test.go, csireverseproxy/pkg/common/constants.go, csireverseproxy/pkg/config/config.go, csireverseproxy/pkg/config/config_test.go, csireverseproxy/pkg/proxy/proxy_test.go, csireverseproxy/test-config/secret-config.yaml
Update unit tests for Secret
| |
=> Update unit tests for Secret

pkg/file/file.go, pkg/file/file_test.go
Targets the `usr/spark/unit-test-improvements` branch, not `main`.
Code coverage above 90% for this package:
```
ok      github.com/dell/csi-powermax/v2/pkg/file        0.039s  coverage: 97.9% of statements
```
Added unit tests for file package
| |
Ran unit tests
=> Added unit tests for file package

csireverseproxy/main.go, csireverseproxy/main_test.go, csireverseproxy/pkg/config/config.go, csireverseproxy/pkg/k8smock/k8smock.go, csireverseproxy/pkg/k8smock/k8smock_test.go, csireverseproxy/test-config/config.yaml, samples/secret/secret.yaml
Updated unit tests for reverseproxy main pkg.
Updated main.go for removing unncessary code checks for secret. 
Updated mock to include a new function for updating secret. 
Refactored unit tests to follow best practices, added more functionality. 
| |
Unit test run several time to ensure success. 
Created new image, deployed on K8S cluster and verified reverseproxy starts ok.
=> Updated unit tests, other minor changes

README.md
Test PR for Staging Pipeline. Please ignore.
=> Test PR for Staging Pipeline

Dockerfile, dell-csi-helm-installer/README.md, dell-csi-helm-installer/csi-install.sh, dell-csi-helm-installer/csi-offline-bundle.md, dell-csi-helm-installer/csi-offline-bundle.sh, dell-csi-helm-installer/verify-csi-powermax.sh
Driver (2.14), K8s and OCP version updates for CSM v1.14
|https://github.com/dell/csm/issues/1707 |
=> Driver (2.14), K8s and OCP version updates for CSM v1.14

go.mod, go.sum, service/step_defs_test.go, service/vsphere_test.go
This PR will update unit test after upgrading govmomi.
This will solve the checks failures in this PR: https://github.com/dell/csi-powermax/pull/507
=> Update unit test

service/controller.go, service/features/service.feature
=> Test ut fixes for maz

service/controller.go, service/controller_test.go
Update of existing UTs.
|https://github.com/dell/csm/issues/1748 |
UT for impacted functions.
=> Fix existing unit tests.

go.mod, go.sum, test/integration/integration_test.go
Updated gocsi commit to include the refactored utils package names.
| https://github.com/dell/csm/issues/1896 |
=> Update gocsi for refactored utils pkg names

service/node.go
This PR addresses an issue where NVMe volumes were not being re-attached to node after the pods consuming them were deleted. The root cause was the CSI driver removing the device symlink under /dev/disk/by-id during the NodeUnstageVolume operation.
With this fix, the driver ensures that the device symlink for NVMe volumes is preserved during NodeUnstageVolume, allowing proper reattachment when a new pod is scheduled.
|dell/csm#1957 |
=> Ensure NVMe Volumes Reattach Correctly After Pod Deletion

service/node.go
This PR addresses an issue where DataVolumes remain stuck in the ImportScheduled state due to importer pods failing to initialize. The root cause was traced to a failure in the CSI driver's NodeStageVolume operation, which logs:
>   Warning  FailedMapVolume          (x8 over 55s)  kubelet                  MapVolume.SetUpDevice failed for volume "techops-f679e8fb01" : rpc error: code = Internal desc = Unable to find device after multiple discovery attempts: at least one NVMe target required
Although NVMeTCP targets from the remote array are successfully discovered and cached, the driver attempts to connect using targets from the local array, resulting in device connection failure.
This update ensures correct target selection during volume staging.
List the GitHub issues impacted by this …
=> Fix NodeStageVolume for Metro NVMe

service/interfaces.go, service/node.go
- Update the disconnectVolume to fail on failed deletion of underlying devices
- Dont use symlink or dm paths for verification
| https://github.com/dell/csm/issues/2010 |
=> Updates DisconnectVolume to correctly fail and clean up the sd disks.

Dockerfile, dell-csi-helm-installer/README.md, dell-csi-helm-installer/csi-install.sh, dell-csi-helm-installer/csi-offline-bundle.md, dell-csi-helm-installer/csi-offline-bundle.sh, service/service_test.go, test/multi-az/testfiles/templates/template-powermax-csm.yaml
Update 2.14 references to 2.15.
|https://github.com/dell/csm/issues/1896 |
=> Update 2.14 references to 2.15
