- dell-csi-helm-installer/verify-csi-powermax.sh
- dell-csi-helm-installer/verify.sh
- helm/csi-powermax/templates/controller.yaml
- helm/csi-powermax/templates/node.yaml
- helm/csi-powermax/values.yaml
- samples/secret/karavi-authorization-config.json
- samples/secret/secret.yaml
This PR implements install support for CSM Authorization sidecar in the helm chart
| https://github.com/dell/csm/issues/78|
- The PowerMax driver is deployed via Helm with Authorization disabled.  Ensured the Authorization sidecar does not get deployed.
- The PowerMax driver is deployed via Helm with Authorization enabled.  Ensured the Authorization sidecar is deployed and works correctly.
- There is an existing cluster with the PowerMax driver deployed and the previous version of the Authorization sidecar deployed.  The Authorization sidecar is upgraded via the driver's helm …
> Add support for CSM Authorization sidecar via Helm

- service/controller.go
- service/mount.go
- service/node.go
- service/storage_group_svc.go
Support for SINGLE_NODE_SINGLE_WRITER and SINGLE_NODE_MULTI_WRITER for kubernetes 1.22+
| |
> RWOP (Read Write Once Pod) support

- go.mod
- go.sum
- helm/csi-powermax/templates/controller.yaml
This PR updates:
- The volume health monitor param for consistent config.
- The dell/gocsi version to the latest version. This will enable us to record CSI REQ/RESP number properly.
| https://github.com/dell/csm/issues/203 |
|https://github.com/dell/csm/issues/206 |
This has been tested through unit and cluster tests.
> Updates VolumeHealthMonitor param & dell/gocsi version

- helm/csi-powermax/values.yaml
Updating the default value of the authorization sidecar to CSM 1.2 version 
| https://github.com/dell/csm/issues/128|
> update default sidecar image version

- samples/storageclass/powermax.yaml
- samples/storageclass/powermax_fc.yaml
- samples/storageclass/powermax_iscsi.yaml
- samples/storageclass/powermax_srdf.yaml
- samples/storageclass/powermax_xfs.yaml
StorageClass parameter fsType is replaced with csi.storage.k8s.io/fstype as it is deprecated.
| https://github.com/dell/csm/issues/188 |
SC, PVC, and pod has been created and the volumes mounted are of the FSType passed in storage class
> StorageClass parameter fsType is replaced with csi.storage.k8s.io/fstype

- Dockerfile.build
- dell-csi-helm-installer/csi-install.sh
- dell-csi-helm-installer/verify-csi-powermax.sh
- helm/csi-powermax/Chart.yaml
- helm/csi-powermax/templates/_helpers.tpl
- helm/csi-powermax/values.yaml
PR has changes for
1. Updating PowerMax version to 2.3 
2. Added k8s 1.24 support and removed k8s 1.21
| https://github.com/dell/csm/issues/243 |
> PowerMax 2.3.0 initial changes

- helm/csi-powermax/templates/csidriver.yaml
- helm/csi-powermax/values.yaml
Added the option for user to configure fsGroup policy  support. 
| https://github.com/dell/csm/issues/285 |
> fsGroup policy support

- helm/csi-powermax/templates/node.yaml
- service/node.go
Fixes node YAML to check if the topology is enabled before creating config map and mounting it.
| https://github.com/dell/csm/issues/300|
Cluster testing:
_root@master-1-pPQwD72vsAduH:~/csi-powermax/dell-csi-helm-installer# kubectl logs powermax-node-rl7cr -n powermax driver
time="2022-05-13T07:53:28Z" level=info msg="Read CSI_LOG_FORMAT: text from configuration file"
time="2022-05-13T07:53:28Z" level=info msg="Read CSI_LOG_LEVEL: debug from config file"
time="2022-05-13T07:53:28Z" level=info msg="Setting log level to debug"
time="2022-05-13T07:53:28Z" level=error msg=**"unable to read topology config file" error="open /node-topology-config/topologyConfig.yaml: no such file or directory"** …
> Fixes node yaml to check for topology enable param

- service/controller.go
- service/deletion_worker.go
* Added support to confiugre muliple NS to single Metro RDFg
* Modified delete_worker.go to issue suspend of the Metro RDFg only when a single RDF LUN exists in that group.
|https://github.com/dell/csm/issues/303|
Cluster Tests
> Ability to configure mulitple NS in a single SRDF Metro RDFg

- dell-csi-helm-installer/verify-csi-powermax.sh
- helm/csi-powermax/Chart.yaml
- helm/csi-powermax/templates/_helpers.tpl
Adding k8 1.21 to support driver installation on latest MKE version.
| https://github.com/dell/csm/issues/243 |
> Adding k8 1.21 to support MKE

- dell-csi-helm-installer/csi-offline-bundle.sh
- helm/csi-powermax/Chart.yaml
Offline bundle installation is failing for PowerMaxmits.
| https://github.com/dell/csm/issues/324 |
Able to deploy driver using the offline bundle.
> Bug Fix: Offline bundle installation is failing for PowerMax

- helm/csi-powermax/values.yaml
This PR updates CSM authorization sidecar to the latest 1.3.0 image. This version change addresses a new rule added to gosec that detects if ReadHeaderTimeout is configured in the http.Server for the sidecar.
|https://github.com/dell/csm/issues/346 |
> Update Authorization Sidecar image to 1.3.0

- service/node.go
It Fixes volume expansion for a volume by removing the namespace from vol ID to get mount info.
|https://github.com/dell/csm/issues/378|
- Unit Tests
- Cluster Test:
```
Check: lsblk -P | awk '/mpath.+pmax-ebd30d8734/ {print $0}'
lsblk -Px MODE | awk '/pmax-ebd30d8734/{if (a && a !~ /pmax-ebd30d8734/) print a; print} {a=$0}'
time="2022-07-15T10:52:26Z" level=info msg="Mount info for volume pmax-ebd30d8734: &{DeviceNames:[sdy sdu sdan sdaj] MPathName:mpathmo MountPoint:/var/lib/kubelet/pods/84022d4c-1cd0-4d86-860d-50dced24505e/volumes/kubernetes.io~csi/pmax-ebd30d8734/mount}"
time="2022-07-15T10:52:26Z" level=info msg="Calling resize the file system" CSIRequestID=44 Size=51540787200 VolumeName=pmax-ebd30d8734 …
```
> Fixes volume expansion when volID has a namespace

- dell-csi-helm-installer/csi-install.sh
During CSI Driver Installation and Upgrade, show a warning to the user for the Unisphere 10.0 upgrade.
|https://github.com/dell/csm/issues/389 |
* Cluster test
> Issue a warning for u4p 10.0 upgrade

- dell-csi-helm-installer/verify-csi-powermax.sh
- go.mod
- go.sum
- helm/csi-powermax/Chart.yaml
- helm/csi-powermax/templates/_helpers.tpl
Adding k8 1.25 support
|https://github.com/dell/csm/issues/478  |
time="2022-09-23T05:38:27-04:00" level=info msg="iscsid.service is not active. Current state - inactive"
time="2022-09-23T05:38:27-04:00" level=info msg="Attempting to start iscsid.service"
time="2022-09-23T05:38:27-04:00" level=error msg="Failed to start iscsid.service. Error - mock - unit is masked - failed to start the unit"
--- PASS: TestEsnureISCSIDaemonIsStarted (0.00s)
PASS
coverage: 72.9% of statements
status 0
ok      github.com/dell/csi-powermax/v2/service 250.644s        coverage: 72.9% of statements …
> Adding k8 1.25 support

- dell-csi-helm-installer/csi-install.sh
- Updates driver installation to
- To skip Unisphere version verification if the skip-verify flag is used.
|https://github.com/dell/csm/issues/491|
- Cluster Installation
> Installation: skip Unisphere version verification when skip-verify flag is passed 

- service/controller.go
- service/deletion_worker.go
- service/replication.go
- Upgrades CreateVolume call to roll back the last added volume in the protected storage group.
- Updated Metro volume deletion to suspend if all the volumes are removed at once
| https://github.com/dell/csm/issues/561|
| https://github.com/dell/csm/issues/552 |
- Unit tests
- Cluster tests
> Upgrades CreateVolume to Rollback on a failure

- service/controller.go
- service/replication.go
- Enhances concurrency for a large number of creating replicated volumes calls.
- Adds additional locks.
- Adds a rollback for the latest volume when the SRDF group becomes non-RDF.
|https://github.com/dell/csm/issues/550 |
- Unit Tests
> Enhances concurrent CreateVolume requests for SRDF volumes

- helm/csi-powermax/templates/controller.yaml
- helm/csi-powermax/templates/node.yaml
- helm/csi-powermax/values.yaml
- service/controller.go
- service/envvars.go
- service/service.go
- service/vsphere.go
Makes variable names consistent for AutoRDM/vSphere across the driver.
|https://github.com/dell/csm/issues/584|
|https://github.com/dell/csm/issues/592|
- Cluster test
> Consistent variable names

- service/controller.go
- Updates the return message in DeleteSnapshot for nonexisting snaps.
- The new error msg is based on Powermax 10.0 API response
|https://github.com/dell/csm/issues/593|
- Unit Test
- 544 scenarios (544 passed)
3865 steps (3865 passed)
- Cluster Test
> Updates the return message in DeleteSnapshot for non existing snaps 

- service/controller.go
- service/replication.go
- Adds feature to create metro volumes from a snapshot
- Adds suspend/resume for SRDF SGs to enable linking of snapshots to newly created SRDF vols.
|https://github.com/dell/csm/issues/609 |
- Unit test
552 scenarios (552 passed)  
3896 steps (3896 passed) PASS ok
- Cluster test
> Enable CSI snapshot restore to Metro Volumes

- go.mod
- go.sum
- helm/csi-powermax/values.yaml
- service/migration.go
- Updated replication/migration extension version as the extensions (https://github.com/dell/dell-csi-extensions/pull/27) and replication module CRD (https://github.com/dell/csm-replication/pull/75) are updated from alpha to v1 version.
- Replicator side car image is updated to v1.4.0.
Note: Since 1.4 replicator side care image is not officially out, please use nightly tag which will be updated when this PR merges.
| https://github.com/dell/csm/issues/432 |
> Updated replication extension & sidecar image version

- helm/csi-powermax/templates/controller.yaml
- helm/csi-powermax/templates/node.yaml
- helm/csi-powermax/values.yaml
- samples/secret/vcenter-secret.yaml
1. Updates the values file to take in a secret name to be used as vCenter cred.
2. Adds a sample secret to be created before using the vSphere feature.
|https://github.com/dell/csm/issues/686 |
- Cluster Test
> Updates vCenter cred to use a Secret

- pkg/migration/migration.go
- samples/storageclass/powermax.yaml
- samples/storageclass/powermax_fc.yaml
- samples/storageclass/powermax_iscsi.yaml
- samples/storageclass/powermax_srdf.yaml
- samples/storageclass/powermax_vsphere.yaml
- samples/storageclass/powermax_xfs.yaml
- service/controller.go
- service/features/service.feature
- service/step_defs_test.go
- A user can use the storage class param to set IO limits on the storage group and its volumes.
- This enables throttling performance and bandwidth of CSI Volumes
|https://github.com/dell/csm/issues/726 |
- Cluster Test
> Feature: Setting up Qos/HostIOLimits on the storage group via storage class

- service/node.go
- Removes namespace from volName before mountInfo call
- Mount info on the node will not have a namespace.
-
|https://github.com/dell/csm/issues/840|
- Unit Test
- Cluster Test
> Removes namespace from volName before mountInfo call

- helm/csi-powermax/templates/_helpers.tpl
- helm/csi-powermax/templates/controller.yaml
- helm/csi-powermax/templates/csidriver.yaml
- helm/csi-powermax/values.yaml
- service/controller.go
Support storagecapacitytracking feature for PowerMax.
Additional context
This feature helps the scheduler to schedule the pod on a node (satisfying the topology constraints) only if the requested capacity is available on the storage array. 
| -----------------|
|https://github.com/dell/csm/issues/876|
> Feature storage capacity tracking

- service/features/service.feature
Updated the Scenario: Call GetCapacity with invalid capabilities
The Unit test for the CSI-PowerMax was failing in the scenario: Call GetCapacity with invalid capabilities. Rectified the error accordingly.
List the GitHub issues impacted by this PR: 
| https://github.com/dell/csm/issues/887 |
Run the unit test manually and also through the automation, All the test got successfully passed.
> Undated the Unit test Scenario.

- service/envvars.go
- service/node.go
- service/service.go
This feature helps in limiting the number of Volume per node by the user.
https://github.com/dell/csm/issues/878
|https://github.com/dell/csm/issues/878 |
Output of the test confirming the volume limits per node 
Events:
Type     Reason            Age   From               Message
----     ------            ----  ----               -------
Warning  FailedScheduling  59s   default-scheduler  0/2 nodes are available: 2 node(s) exceed max volume count. preemption: 0/2 nodes are available: 2 No preemption victims found for incoming pod.
> Feature max vol limits

- core/semver/semver.go
- service/node.go
"io/ioutil" has been deprecated since Go 1.19: As of Go 1.16
| https://github.com/dell/csm/issues/916 |
> chore: remove refs to deprecated io/ioutil

- Dockerfile.build
- csireverseproxy/Dockerfile
- csireverseproxy/manifests/revproxy.yaml
- dell-csi-helm-installer/csi-install.sh
- dell-csi-helm-installer/verify-csi-powermax.sh
Adding k8 28 support
updating driver/helm version 
| https://github.com/dell/csm/issues/947 |
> Adding k8 28 support

- service/features/service.feature
- service/node.go
- service/service_test.go
- service/step_defs_test.go
- test/integration/features/integration.feature
This feature helps in limiting the number of Volume per node by the user. This PR is part of unit testing for the volume_limits feature.
|https://github.com/dell/csm/issues/878|
> Vol limits csi power max test case

- service/mount.go
- service/node.go
Adds error-checks for general OS errors
|https://github.com/dell/csm/issues/1014|
- Unit Tests
> Adds error-checks for general OS errors

- .build.config
- build.sh
Use common base image
If building for ubimicro, download the csm-common.mk file and use that specified UBI micro image instead of relying on the .build.config file.
| https://github.com/dell/csm/issues/1031 |
> Use common base image

- Makefile
Fixing make command error for gosec
| https://github.com/dell/csm/issues/1053|
> Fixing make command error for gosec

- README.md
- test/integration/README
Updating Readme files 
|https://github.com/dell/csm/issues/1056 |
> Adding link to runtime dependencies in README file 

- .github/workflows/linters.yaml
- pkg/file/file.go
- service/controller.go
- service/deletion_worker.go
- service/gobrick_mock_test.go
- service/gosystemd_mock.go
- service/identity.go
- service/interfaces.go
- service/migration.go
- service/mount.go
- service/node.go
- service/replication.go
- service/service.go
- service/service_test.go
- service/service_unit_test.go
- service/snap.go
- service/step_defs_test.go
- service/storage_group_svc.go
- test/integration/step_defs_test.go
Fixing linting errors 
| https://github.com/dell/csm/issues/926 |
> Fixing linting errors

- csireverseproxy/go.mod
- go.mod
Updating go version to latest available i.e. => 1.22
> go version bump-up

- service/controller.go
- service/identity.go
- service/step_defs_test.go
- test/integration/step_defs_test.go
Fixing protobuf errors
| https://github.com/dell/csm/issues/1239 |
> Fixing protobuf errors

- dell-csi-helm-installer/verify.sh
Since we are relaxing the constraint on helm installation to higher kubernetes distro, we add the warning message
This relates to that PR: https://github.com/dell/helm-charts/pull/410
And ticket : KRV-13492
Not tested
> Add warning message if an higher k8s version is tested

- service/controller.go
- service/csi_extension_server.go
- service/features/csi_extension.feature
- service/features/delete_volume.feature
- For improving performance, we reverse the order to check block volume first and then file.
- Updated unit tests
| https://github.com/dell/csm/issues/1370|
- Cluster Test
- Unit Test
> Check for block volume first and then file

- go.mod
- go.sum
- Updates gobrick to 1.11.1
- This updates the rescan logic to use LUN number
| https://github.com/dell/csm/issues/1379|
- Unit Test
- Cluster Test
> Updates gobrick to 1.11.1

- csireverseproxy/pkg/standaloneproxy/standaloneproxy.go
- service/node.go
This PR:
- Rearrange Protocol Preference for automatic selection
- NVMeTCP > FC > ISCSI
- Selects NVMeTCP or FC over iscsi if iSCSI initiators are also present on the host.
|https://github.com/dell/csm/issues/1388|
> Rearrange Protocol preferences for its automatic selection

- .github/workflows/actions.yaml
- Makefile
- service/controller.go
- service/csi_extension_server.go
- service/deletion_worker.go
- service/migration.go
- service/node.go
- service/replication.go
- service/service_unit_test.go
- service/step_defs_test.go
- test/integration/step_defs_test.go
Enabling unit tests for PR and merge builds. Had to specify the action to skip the testgodog tests. This will enable some unit tests to be run and sets things up for future PRs to run unit tests.
|[1422](https://github.com/dell/csm/issues/1422)|
Tested by running unit tests and running GitHub actions.
> Enable unit tests in PR and merge builds

- service/controller.go
To support volumes with tenant prefixes with Authorization v2, the volume flows should use the volume identifier from the array..
| https://github.com/dell/csm/issues/1281|
> [feature-1281]: Use volume identifier from array response to support Authorization v2

- Makefile
- build.sh
- service/node.go
Image build job fails because of no space left on the build machine. This is caused by overlay images created during the build process
| https://github.com/dell/csm/issues/1448 |
> Added make target to build without cache

- go.mod
- go.sum
Update to the PowerStore driver to use the gobrick with the NVMe matching fix for issue 1469. This issue prevents successful mounting of PowerStore devices when using the NVMe protocols.
| https://github.com/dell/csm/issues/1469 |
> Fix wwm matching failure on NVMe mounts

- service/service.go
Introducing a error check for setting array related data to envs in csi-powermax
| https://github.com/dell/csm/issues/1499 |
Ran sucessful gosec./... test and make unit-test with screenshots below
> Fixed Defect in service.go

- test/integration/features/integration.feature
- test/integration/step_defs_test.go
Description
This change will solve the integration test failures for first 16 test cases.
https://github.com/dell/csm/issues/1519
I have tested this change locally . Attaching logs and xml file.
[success_logs.txt](https://github.com/user-attachments/files/17345330/success_logs.txt)
[success_logs2.txt](https://github.com/user-attachments/files/17348337/success_logs2.txt)
```
<testsuites name="CSI Powermax Int Tests" tests="7" skipped="0" failures="0" errors="0" time="341.480639987">
<testsuite name="Powermax OS CSI interface" tests="7" skipped="0" failures="0" errors="0" time="341.479148273">
<testcase name="Create and delete basic thick large volume" status="passed" time="39.710621473"/>
<testcase name="Create and delete basic volume using Gold Service Level" …
```
> Fix PowerMax Integration test failures

- README.md
- service/controller.go
- test/helm/1clonevol/templates/pvc0.yaml
- test/helm/2vols+restore/templates/createFromSnap.yaml
- test/helm/2vols+restore/templates/pvc0.yaml
- test/helm/2vols+restore/templates/pvc1.yaml
- test/helm/2vols+restore/templates/test.yaml
- test/helm/snaprestoretest.sh
- test/helm/starttest.sh
-- Note: this is identical to an earlier PR with unsigned commits --
Currently, when the csi-powermax takes a snapshot of a volume, it does not set a RestoreSize for the snapshot. This PR adds the sizeInBytes field to the snapshot to set the RestoreSize. The following additional work is also done:
1) Add clarification to README about building the PMax image.
2) Fix several places in the helm tests where a namespace was hardcoded.
3) Update some deprecated `kubectl exec` commands in helm tests.
4) Update the size of the pvc being restored to in the `2vols+restore` helm test to 8194Mi -- even though the requested size of the original volume was 8Gi (8192Mi), PMax rounds to the next cylinder boundary, which gives the pvc an actual size of 8194Mi. A separate doc PR will go up in relation to …
> Add RestoreSize to VolumeSnapshot

- go.mod
- go.sum
- service/node.go
Fix nvme block resize.
| https://github.com/dell/csm/issues/1534 |
> Fix nvme block resize

- test/integration/README
- test/integration/README.md
Update integration test readme with the following:
1. Change the file from README to README.md so that markdown works.
2. Update the steps for running the integration test to ones that actually work.
3. Add a note on replication test cases that are not currently working due to issues in the tests themselves.
| |
This is only a README change. Tested the steps in the README and confirmed that I am able to run the integration tests.
> Update integration test README

- .github/workflows/actions.yaml
- csireverseproxy/deploy/config.yaml
- csireverseproxy/test-config/config.yaml
- pkg/symmetrix/powermax.go
- pkg/symmetrix/powermax_test.go
- test/integration/step_defs_test.go
The sample secret names used in the sample reverseproxy configmap yaml are unclear. This PR makes it clear which endpoint each secret is for. There is an accompanying doc PR for this clarification.
Additionally, a few unrelated variable names were changed to comply with linting, and I added a unit test to cover the code where I changed the variable name.
| https://github.com/dell/csm/issues/1568 |
Ran unit tests for both driver and reverseproxy. No integration tests run because these changes are not touched by integration tests (there are no code changes).
> Clarify which secret is for which unisphere in reverseproxy configmap

- samples/configmap/powermax-array-config.yaml
Updating default value for X_CSI_TRANSPORT_PROTOCOL in the comment section of powermax-array-config.yaml
|https://github.com/dell/csm/issues/1638|
> Updating default value for X_CSI_TRANSPORT_PROTOCOL

- service/features/node_publish_unpublish.feature
- service/node.go
- service/storage_group_svc.go
Ignored case difference for host name when X_CSI_IG_MODIFY_HOSTNAME is enabled. So, existing host with different case will be considered instead of modifying it which fails.
| https://github.com/dell/csm/issues/1650 |
The issue was reproduced on my setup and the node pod crashed.
Then with the fix on the same setup, the node pod didn't crash. 
```
time="2024-12-19T21:49:29Z" level=info msg="**************************nodeHostSetup executing...*******************************"
time="2024-12-19T21:49:29Z" level=info msg="Waiting for 10 seconds"
time="2024-12-19T21:49:39Z" level=info msg="valid FC initiators: []"
time="2024-12-19T21:49:39Z" level=info msg="No existing NVMe hosts; new hosts will be created for all …
```
> Ignore case difference for host name when X_CSI_IG_MODIFY_HOSTNAME is enabled

- csireverseproxy/pkg/k8sutils/k8sutils.go
Ignored the Gosec warning for the AddEventHandler function, as it doesn't return any errors, but Gosec is flagging it for potential unhandled errors.
| https://github.com/dell/csm/issues/1559 |
gosec reported no errors:
> Gosec CWE fix

- .github/workflows/auto-release.yaml
- .github/workflows/go-version.yaml
- .github/workflows/release.yaml
Added driver release action
|----------------|
|  https://github.com/dell/csm/issues/1490  |
Tested against forked repo: https://github.com/harishp8889/test-powerstore-automation/actions/runs/12351664554/job/34467105602
> Added driver release action

- Dockerfile
- csireverseproxy/Dockerfile
Added the required labels to the image container so that it can pass preflight checks.
| https://github.com/dell/csm/issues/1667 |
Built images. Docker inspect show:
"Labels": {
"architecture": "x86_64",
"build-date": "2024-08-27T19:24:54",
"com.redhat.component": "ubi9-micro-container",
"com.redhat.license_terms": "https://www.redhat.com/en/about/red-hat-end-user-license-agreements#UBI",
"description": "CSI Driver for provisioning persistent storage from Dell EMC PowerMax",
"distribution-scope": "public",
"io.buildah.version": "1.29.4",
"io.k8s.description": "Very small image …
> Add preflight required labels.

- service/features/service.feature
- service/service.go
- service/service_test.go
- service/step_defs_test.go
Set default values for replication prefix in the driver since replicator sidecar is not needed for Metro feature.
With this, the driver will not fail the Metro request irrespective of the deployment method used.
| https://github.com/dell/csm/issues/1711 |
Metro volume was created successfully and then deleted, with just the driver installed without the replication module or the replicator sidecar.
```
[root@koc1-bastion-10-247-96-100 powermax_309_836]# k get pv | grep metro
csivol-d642603e51   10487040Ki   RWO            Delete           Bound         default/my-pvc  
powermax-metro              <unset>                          13m
[root@koc1-bastion-10-247-96-100 powermax_309_836]# k get pvc | grep metro …
```
> Metro: Set default value for replication prefixes

- csireverseproxy/main.go
- csireverseproxy/pkg/common/constants.go
- csireverseproxy/pkg/config/config.go
- csireverseproxy/pkg/config/config_test.go
- service/service.go
1. Update reversepoxy to use powermax-config-params to infer port, log level etc. 
2. Simplified the watcher logic to use parameterized viper instances as opposed to global instances. 
3. Reverted back to throwing/return error when PrimaryEndpoint of a storage array does not have mapping entry under management servers.
4. Fixed prior review comments. 
| (https://github.com/dell/csm/issues/1614)|
Manually tested mounted, secret and configmap cases with multiple arrays. Tested watcher logic by modifying params on the fly after the proxy is up and running.
> Changes to revproxy to use mounted cm for params

- csireverseproxy/Dockerfile
- csireverseproxy/go.mod
- csireverseproxy/main.go
- csireverseproxy/main_test.go
- csireverseproxy/pkg/config/config.go
- csireverseproxy/pkg/config/config_test.go
- csireverseproxy/pkg/k8smock/k8smock.go
- csireverseproxy/pkg/k8smock/k8smock_test.go
- csireverseproxy/pkg/k8sutils/k8sutils.go
- csireverseproxy/pkg/proxy/proxy.go
- csireverseproxy/pkg/proxy/proxy_test.go
- csireverseproxy/pkg/servermock/servermock.go
- csireverseproxy/pkg/utils/locks.go
- csireverseproxy/pkg/utils/utils.go
PR to update the reverseproxy module, so that the module can be imported, and functions can be reused in the observability module. 
| |
Able to successfully build the images and Install the Driver.
> Updating reverseproxy module

- provider/provider_test.go
PR targets the `usr/spark/unit-test-improvements` branch.
Increases code coverage for provider package to 100%:
```
ok      github.com/dell/csi-powermax/v2/provider        0.040s  coverage: 100.0% of statements
```
| |
Ran the new unit tests for the provider package.
> Update unit tests for provider package

- pkg/migration/migration_test.go
This PR is targeting the `usr/spark/unit-test-improvements` branch and not `main`.
Added tests for migration package to increase coverage to 90.5%.
```
ok      github.com/dell/csi-powermax/v2/pkg/migration   0.032s  coverage: 90.5% of statements
```
| |
Ran unit tests for this package.
```
ok      github.com/dell/csi-powermax/v2/pkg/migration   0.032s  coverage: 90.5% of statements
```
> Added tests for migration package

- main.go
- main_test.go
Adding unit tests to main to bring coverage for `main.go` to 93%+.
Refactored main to accommodate dependency injection for testing.
| |
Built a new image for the driver, deployed and tested via `cert-csi certify` with both a single controller and multiple controller replicas.
> Refactor main and add unit tests

- csireverseproxy/main.go
- csireverseproxy/pkg/k8sutils/k8sutils.go
- csireverseproxy/pkg/k8sutils/k8sutils_test.go
csireverseproxy/pkg/k8sutils - UT improvements to bring the coverage to > 90%
K8sUtils.go needed some refactoring to enable mocking of functions that rely on a really k8s cluster. Those functions are now injected. 
| |
Unit test: ok      revproxy/v2/pkg/k8sutils        0.347s  coverage: 91.4% of statements
cert-csi (with image built from this branch) : 
Tests:
--------------------------------------------------------------
1. TestCase: VolumeIoSuite
Started:   2025-02-06 17:19:57.780393693 +0000 UTC
Ended:     2025-02-06 17:30:38.373937927 +0000 UTC
Result:    SUCCESS
Stage metrics:
PVCBind:
Avg: 17.382461335s
Min: 15.589933826s
Max: 20.551724538s
Histogram: …
> csireverseproxy/pkg/k8sutils - UT improvements

- csireverseproxy/pkg/proxy/proxy.go
- csireverseproxy/pkg/proxy/proxy_test.go
- csireverseproxy/test-config/config.yaml
- csireverseproxy/test-config/configB.yaml
- csireverseproxy/test-config/configB_single.yaml
- csireverseproxy/test-config/configB_single_noBackup.yaml
- csireverseproxy/test-config/configC_single.yaml
Add unit tests for the `proxy` package and ensure that it is greater than the 90% threshold.
| |
**Proxy Coverage**
```
PASS
coverage: 91.7% of statements
ok      revproxy/v2/pkg/proxy   0.053s  coverage: 91.7% of statements
```
**Complete Run**
<details>
```
$ make unit-test
go test -v -coverprofile c.out ./...
time="2025-02-10T12:08:50-05:00" level=info msg="Creating primary mock server..."
time="2025-02-10T12:08:50-05:00" level=info msg="Primary mock server listening on https://127.0.0.1:9104"
time="2025-02-10T12:08:50-05:00" level=info msg="Creating backup mock server..." …
```
> Add Proxy Package Tests for ReverseProxy

- csireverseproxy/go.mod
- csireverseproxy/main.go
- csireverseproxy/main_test.go
- csireverseproxy/manifests/revproxy.yaml
- csireverseproxy/pkg/config/config.go
- csireverseproxy/pkg/config/config_test.go
- csireverseproxy/pkg/k8smock/k8smock.go
- csireverseproxy/pkg/k8smock/k8smock_test.go
- csireverseproxy/pkg/k8sutils/k8sutils.go
- csireverseproxy/pkg/k8sutils/k8sutils_test.go
- csireverseproxy/test-config/config.yaml
Increase UT coverage for main and pkg/config in csireverseproxy. Note: This is not merge to MAIN but to usr/spark/unit-test-improvements branch.  
Note: 
1. unused functions ( a couple of DeepCopy) were removed. 
2. StartInformer signature modified, was not returning anything but nil 
3. Some structs were moved to the top of file for better readability. 
4. Methods in main.go main() and run() are now dependency injected to improve testability. 
| |
Unit test run: 
ok      revproxy/v2/pkg/config  0.995s  coverage: 90.9% of statements
ok  	revproxy/v2	3.616s	coverage: 90.3% of statements
cert-csi run with image built from this branch:
Tests:
--------------------------------------------------------------
1. …
> csireverseproxy - improve UT coverage 

- csireverseproxy/main_test.go
- csireverseproxy/pkg/cache/cache_test.go
- csireverseproxy/pkg/utils/locks_test.go
Resolving some data races observed in tests for csireverseproxy module.
> Note: these are being merged to the branch for ongoing efforts to increase code coverage.
| |
Ran several test runs with `-race` flag enabled and received no data race warnings.
```bash
[csireverseproxy]$ sudo go test -race -cover -timeout 30s ./...
ok      revproxy/v2     4.734s  coverage: 90.3% of statements
ok      revproxy/v2/pkg/cache   1.073s  coverage: 100.0% of statements
ok      revproxy/v2/pkg/common  3.138s  coverage: 92.0% of statements
ok      revproxy/v2/pkg/config  1.428s  coverage: 90.9% of statements
ok      revproxy/v2/pkg/k8smock 1.294s  coverage: 92.4% of statements
ok      revproxy/v2/pkg/k8sutils        1.253s …
```
> Fix data races in reverse proxy unit tests

- service/deletion_worker.go
- service/locks.go
Refactoring adding volumes to deletion queue
Running `populateDeletionQueue()` as a goroutine was causing data races with unsafe concurrent access to the http client of the powermax client while running powermax REST API queries.
Instead of running the whole function as a goroutine, only create goroutines for queue insertion operations. Since the queue insertion function needs no reference to the powermax client, there should be no issues.
Also removed a log message in locks.go that printed every 20ms.
| |
> Fix data race in deletion_worker.go

- go.mod
PR for updating the go version of go.mod to v1.23.0, to make it consistent with the go version specified in csm-common.mk
There are issues seen while building the image for CSI Powermax and Reverse Proxy from the main branch due to inconsistency in the go version in the go.mod file of CSI Powermax and go version mentioned in csm-common.mk which is used for building the images - https://github.com/dell/csm/blob/main/config/csm-common.mk#L30
| |
> Updating Go Version in go.mod

- Makefile
- README.md
- csireverseproxy/Dockerfile
- csireverseproxy/Makefile
The reverseproxy image build is building twice. This may have been due to the legacy Dockerfile, before the two build was introduced. Also cleaned up some obsolete build targets and Go build options.
| |
Ran the two images the verify that they start without any linker errors. Installed driver and proxy in K8s cluster. Ran cert-csi vio test suite.
> Cleanup obsolete Makefile/Dockerfile entries.

- service/controller.go
- service/features/snapshot.feature
- service/step_defs_test.go
This PR updates the SizeBytes field in the csi.Snapshot structure to use the volume capacity in gigabytes (vol.CapacityGB) instead of the previous calculation based on cylinder size. This change ensures that the snapshot size is accurately represented in bytes.
| https://github.com/dell/csm/issues/1792|
Ran Cert-csi
> Updated the snapshot size

- go.mod
- service/snap.go
- service/snap_test.go
SnapID is a string name, calculated via:
```
snapID := fmt.Sprintf("%s%s-%d", TempSnap, s.getClusterPrefix(), time.Now().Nanosecond())
```
When creating a volume from a volume, we pass this string to CreateSnapshotFromVolume, and then pass the same name to LinkVolumeToSnapshot. 
We assume the name returned from a snapshot created by CreateSnapshotFromVolume will still equal snapID, but this is not the case when the driver is deployed with Authorization because when auth is deployed, the snapshot gets the tenant volumePrefix added to the beginning of its name. 
This causes an issue in LinkVolumeToSnapshot, because we call it with the outdated snapID name: 
```
err = s.LinkVolumeToSnapshot(ctx, symID, vol.VolumeID, tgtDevID, snapID, reqID, isCopy, pmaxClient)
```
this results in an error …
> Set snapID to the snapshotName returned in snapInfo

- service/node.go
Get the SymIDs from reverse-proxy configmap instead when secret doesnt contain managed arrays.
|https://github.com/dell/csm/issues/1707 |
Ran UT to make sure the SymIds are populated. Verified fix with new image and testing if HostIDs are creating and it was.
This is with Nightly image : Nodehostsetup starts and stops as it couldnt find SymIds
This is a test image with this fix :
> Get SymID from configmap if secret doesnt exist

- csireverseproxy/pkg/common/constants.go
- csireverseproxy/pkg/utils/utils.go
Ensure that with the latest `gosec` changes in the common GitHub actions that `reverseproxy` is covered.
| https://github.com/dell/csm/issues/1490 |
> Fix: Ensure Gosec Runs on Reverseproxy

- csireverseproxy/main_test.go
Fix csireversperoxy unit tests by adding retries that timeout.
| https://github.com/dell/csm/issues/1707|
> retry for race condition failures

- service/service.go
- service/service_test.go
Updated requirements clarification. A node that is zoned to an array must not access arrays that are not zoned. Also add check for case where two arrays could be zoned.
|https://github.com/dell/csm/issues/1748|
> Restrict zoned nodes from accessing unzoned arrays

- test/helm/10block/templates/test.yaml
- test/helm/10vols/templates/test.yaml
- test/helm/1bigvol/templates/test.yaml
- test/helm/1clonevol/templates/test.yaml
- test/helm/1vol-rep/templates/test.yaml
- test/helm/1vol/templates/test.yaml
- test/helm/2block/templates/test.yaml
- test/helm/2vols+clone/templates/test.yaml
- test/helm/2vols+restore/templates/test.yaml
- test/helm/2vols/templates/test.yaml
- test/helm/7vols/templates/test.yaml
- test/helm/README.md
- test/helm/block/templates/test.yaml
- test/helm/xfspre/templates/test.yaml
The PR addresses the CentOS image name in all test yaml files and replaces docker path with quay.
Also It introduces a small update to the Helm tests readme file.
|https://github.com/dell/csm/issues/1893|
> Helm test README and CentOS image updates

- service/node.go
This PR addresses an issue where NVMe volumes were not being re-attached to node after the pods consuming them were deleted. The root cause was the CSI driver removing the device symlink under `/dev/disk/by-id` during the NodeUnstageVolume operation.
With this fix, the driver ensures that the device symlink for NVMe volumes is preserved during NodeUnstageVolume, allowing proper reattachment when a new pod is scheduled.
|https://github.com/dell/csm/issues/1957 |
> Ensure NVMe Volumes Reattach Correctly After Pod Deletion
